### ISSUE TITLE
Need Update Script.

### ISSUE THREAD

**Issue by JetPackInc** [JetPackInc/The-Bot-iOX-Project#10]
No Way to Update BOT-iOX. We do not have a automatic update script, we are looking for good coders that could make this happen.

**Comment by JetPackInc** [comment]
We will be releasing v2.0 when this is fixed

**Comment by unipixstudio** [comment]
ok.......
.....

**Comment by JetPackInc** [comment]
I have fixed this issue and made UPDATING.md I will now close this issue.
